### ISSUE TITLE
[求教] 关于SPH的入门

### ISSUE THREAD

**Issue by houkensjtu** [lyd405121/wcsph#1]
你好！我在Taichi论坛和这里看到你实现了很多SPH相关的算法和不同效果，想请教一下你如果想入门学习最基础的SPH算法有什么推荐的资料或者是在Github上的开源代码吗？谢谢！

**Comment by lyd405121** [comment]
---------------开源代码-----------------
胡博视频中提到的：
https://github.com/InteractiveComputerGraphics/SPlisHSPlasH

-----------------教程-------------------------
https://interactivecomputergraphics.github.io/SPH-Tutorial/
从第一章开始入门比较好
https://interactivecomputergraphics.github.io/SPH-Tutorial/slides/01_intro_foundations_neighborhood.pdf

-----------------必读经典--------------------------
Particle-Based Fluid Simulation for Interactive Applications
被引用次数1700

**Comment by houkensjtu** [comment]
灰常感谢！我知道胡神视频里安利的那个tutorial，不过最后的那个论文我之前不知道，一定要拿来读一读:)
